spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - "*"

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /oauth2/**
          filters:
            - StripPrefix=1


        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctor/**
          filters:
            - StripPrefix=1
            - JwtValidation


        - id: clinic-service
          uri: lb://clinic-service
          predicates:
            - Path=/clinic/**
          filters:
            - StripPrefix=1
            - JwtValidation


        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
          filters:
            - StripPrefix=1
            - JwtValidation


        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
          filters:
            - StripPrefix=1
            - JwtValidation

server:
  port: 8765